"""Contradiction-aware hypothesis ranking with interaction influence rules.

v3 spec Section 11 — Influence Resolution:
  Tier 0: Interaction / stack-up hypothesis with observation support (generated by
          pattern triggers, not document-listed causes).
  Tier 1: Non-contradicted hypothesis with at least one supporting alignment.
  Tier 2: Non-contradicted hypothesis with zero support (cannot be PRIMARY if
          a supported alternative exists).
  Tier 3: Contradicted, negative-scored, or weakening-dominated hypothesis.

Interaction influence rule (v3 spec Section 11):
  When a CUMULATIVE_STACKUP or COMPOUNDING_MULTI_FACTOR hypothesis has observation
  support, single-process explanations are down-tiered because the interaction
  pattern provides a more complete explanation.
"""

from __future__ import annotations

from aiqe_rca.engine.pattern_facts import (
    INTERACTION_TEMPLATE_IDS,
    SINGLE_PROCESS_TEMPLATE_IDS,
    PatternFact,
    trigger_stackup_interaction,
)
from aiqe_rca.models.alignment import AlignmentLabel, AlignmentResult
from aiqe_rca.models.gaps import DataGap, GapSeverity
from aiqe_rca.models.hypothesis import Hypothesis, RankLabel


def _count_alignments(
    hypothesis_id: str,
    alignments: list[AlignmentResult],
) -> tuple[int, int, int, int]:
    """Return supporting, weakening, contradictory, and indeterminate counts."""
    supporting = weakening = contradictory = indeterminate = 0
    for alignment in alignments:
        if alignment.hypothesis_id != hypothesis_id:
            continue
        if alignment.classification == AlignmentLabel.SUPPORTING:
            supporting += 1
        elif alignment.classification == AlignmentLabel.WEAKENING:
            weakening += 1
        elif alignment.classification == AlignmentLabel.CONTRADICTING:
            contradictory += 1
        else:
            indeterminate += 1
    return supporting, weakening, contradictory, indeterminate


def _compute_gap_severity(hypothesis_id: str, gaps: list[DataGap]) -> int:
    severity = 0
    for gap in gaps:
        if hypothesis_id not in gap.affects_hypotheses:
            continue
        if gap.severity == GapSeverity.CRITICAL:
            severity += 2
        elif gap.severity == GapSeverity.MODERATE:
            severity += 1
    return severity


def _score_hypothesis(
    supporting: int,
    weakening: int,
    contradictory: int,
    gap_penalty: int,
) -> int:
    return (supporting * 2) - weakening - (contradictory * 3) - gap_penalty


def rank_hypotheses(
    hypotheses: list[Hypothesis],
    alignments: list[AlignmentResult],
    gaps: list[DataGap],
    pattern_facts: list[PatternFact] | None = None,
) -> list[Hypothesis]:
    """Rank hypotheses using v3 tier-based deterministic influence rules.

    Args:
        hypotheses:     Candidate hypotheses to rank.
        alignments:     Observation-only evidence classifications.
        gaps:           Data gap objects.
        pattern_facts:  Optional pattern facts from the pattern fact layer;
                        used to apply the interaction influence rule.
    """
    pattern_facts = pattern_facts or []

    # --- Compute scores and counts ---
    counts: dict[str, tuple[int, int, int, int]] = {}
    for h in hypotheses:
        s, w, c, i = _count_alignments(h.id, alignments)
        counts[h.id] = (s, w, c, i)
        h.gap_severity = _compute_gap_severity(h.id, gaps)
        h.net_support = _score_hypothesis(s, w, c, h.gap_severity)

    # --- Interaction influence rule (v3 spec Section 11) ---
    # When a stack-up / interaction pattern is detected AND at least one
    # interaction-class hypothesis has observation support, single-process
    # explanations are weakened by reducing their effective net_support.
    interaction_active = trigger_stackup_interaction(pattern_facts)
    interaction_has_support = any(
        h.template_id in INTERACTION_TEMPLATE_IDS and counts[h.id][0] > 0
        for h in hypotheses
    )
    if interaction_active and interaction_has_support:
        for h in hypotheses:
            if h.template_id in SINGLE_PROCESS_TEMPLATE_IDS:
                # Apply influence penalty: single-process loses one support-equivalent
                h.net_support -= 2

    # --- Tier function for deterministic sorting ---
    def _tier(h: Hypothesis) -> tuple:
        s, w, c, _ = counts[h.id]

        # Interaction hypothesis with support → highest priority (tier 0)
        if h.template_id in INTERACTION_TEMPLATE_IDS and s > 0 and c == 0:
            primary_tier = 0
        # Non-contradicted, supported → tier 1
        elif s > 0 and c == 0:
            primary_tier = 1
        # Non-contradicted, unsupported → tier 2 (cannot be PRIMARY if tier-1 exists)
        elif c == 0:
            primary_tier = 2
        # Contradicted or negative → tier 3
        else:
            primary_tier = 3

        return (
            primary_tier,
            -int(s > 0),          # prefer supported over unsupported within tier
            c,                     # fewer contradictions is better
            w,                     # fewer weakenings is better
            h.gap_severity,        # fewer gap penalties is better
            h.id,                  # stable tiebreaker
        )

    ranked = sorted(hypotheses, key=_tier)

    # --- Rule: zero-support hypothesis cannot hold PRIMARY if supported alternative exists ---
    has_supported = any(counts[h.id][0] > 0 for h in ranked)
    if has_supported and counts[ranked[0].id][0] == 0:
        supported = [h for h in ranked if counts[h.id][0] > 0]
        if supported:
            new_primary = supported[0]
            ranked = [new_primary] + [h for h in ranked if h.id != new_primary.id]

    # --- AG-3 Rev-C: all-unsupported fallback ---
    # If NO hypothesis has at least one direct observation support alignment,
    # the report must NOT label any hypothesis "Primary Contributor". All are
    # labeled "Unresolved Competing Hypothesis" and confidence is forced LOW.
    has_any_support = any(counts[h.id][0] > 0 for h in ranked)
    if not has_any_support:
        # Sort by fewest gaps → fewest contradictions → fewest weakenings → stable id
        unresolved = sorted(
            ranked,
            key=lambda h: (
                h.gap_severity,
                counts[h.id][2],
                counts[h.id][1],
                h.id,
            ),
        )
        for h in unresolved:
            h.rank_label = RankLabel.UNRESOLVED
        hypotheses[:] = unresolved
        return hypotheses

    # --- Assign rank labels (normal path — at least one supported hypothesis) ---
    secondary_assigned = False
    for index, h in enumerate(ranked):
        s, w, c, _ = counts[h.id]
        if index == 0:
            h.rank_label = RankLabel.PRIMARY
            continue
        is_false_lead = (
            c > 0
            or h.net_support < 0
            or w >= max(s, 1)
        )
        if is_false_lead:
            h.rank_label = RankLabel.DEPRIORITIZED
            continue
        if not secondary_assigned:
            h.rank_label = RankLabel.SECONDARY
            secondary_assigned = True
        else:
            h.rank_label = RankLabel.CONDITIONAL_AMPLIFIER

    hypotheses[:] = ranked
    return hypotheses
