"""Hypothesis data models."""

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class RankLabel(str, Enum):
    """Hypothesis ranking labels."""

    PRIMARY = "Primary Contributor"
    SECONDARY = "Secondary Contributor"
    CONDITIONAL_AMPLIFIER = "Conditional Amplifier"
    UNRANKED = "Unranked"


class Hypothesis(BaseModel):
    """A candidate root cause hypothesis generated by the engine."""

    id: str = Field(description="Unique hypothesis ID (e.g., H1)")
    description: str = Field(description="Plain-language hypothesis description")
    template_id: Optional[str] = Field(
        default=None, description="ID of the domain template that generated this"
    )
    process_step: Optional[str] = Field(
        default=None, description="Related process step or component"
    )
    rank_label: RankLabel = RankLabel.UNRANKED
    keywords: list[str] = Field(default_factory=list)
    net_support: int = Field(default=0, description="Internal score: supporting - contradicting")
    gap_severity: int = Field(default=0, description="Internal gap impact score")
    associated_evidence_ids: list[str] = Field(default_factory=list)

    def __hash__(self) -> int:
        return hash(self.id)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Hypothesis):
            return False
        return self.id == other.id
